# Generated by Django 4.0.4 on 2022-04-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Address',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='Gender',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
